name: ForSyDe-Deep
description: A Deep-Embedded Synthesizer for ForSyDe Models
remote_theme: ugeorge/forsyde-web-theme

url: https://forsyde.github.io/forsyde-deep
parent-url: https://forsyde.github.io

maintainer:
  name: ugeorge
  url: https://github.com/ugeorge

github-releases:
  zip_url: https://api.github.com/repos/forsyde/forsyde-deep/zipball/master
  tar_url: https://api.github.com/repos/forsyde/forsyde-deep/tarball/master

## paths to exclude from the site generation
exclude: [Gemfile, Gemfile.lock, README.md, LICENSE, Setup.hs, setup.html, src, tests, '*cabal*', dist, lib, examples]

plugins:
- jekyll-seo-tag
- jekyll-remote-theme
- jekyll-sitemap
