resolver: ghc-8.0.2

extra-deps:
- mtl-2.2.2
- parameterized-data-0.1.6
- random-1.1
- regex-posix-0.95.2
- syb-0.7
- type-level-0.3.0
- regex-base-0.93.2
# for test suites
- HUnit-1.6.0.0
- QuickCheck-2.12.6.1
- call-stack-0.1.0
- erf-2.0.0.0
- tf-random-0.5
- primitive-0.6.4.0
