-- Automatically generated by ForSyDe
library forsyde;
library ieee;
use forsyde.types.all;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
library mingzi_lib;
use mingzi_lib.types.all;


entity \mingzi\ is
     port (\in\ : in fsvec_2_fsvec_2_int32;
           \out\ : out fsvec_2_fsvec_2_int32);
end entity \mingzi\;


architecture synthesizable of \mingzi\ is
     signal \proc1_out\ : fsvec_2_fsvec_2_int32;
begin
     \proc1\ : block
          port (\proc1_in1\ : in fsvec_2_fsvec_2_int32;
                \proc1_out\ : out fsvec_2_fsvec_2_int32);
          port map (\proc1_in1\ => \in\,
                    \proc1_out\ => \proc1_out\);
          function \takeProcFun_0\ (\x_0\ : fsvec_2_fsvec_2_int32)
                                   return fsvec_2_fsvec_2_int32 is
          begin
               return \x_0\;
          end;
     begin
          \proc1_out\ <= \takeProcFun_0\(\x_0\ => \in\);
     end block \proc1\;
     
     \out\ <= \proc1_out\;
end architecture synthesizable;
